Add 'transparent' flag to 'add' to allow creation of non-Busy (Free) …
insanum/gcalcli pull request #509
Opened 2020-01-29 05:22 UTC by kda

…events.

I use this to create all day events frequently.  I don't want the day marked busy.
So, I added this.

2020-01-29 06:02 UTC, jcrowgey commented
This seems like a useful addition.  But this needs a little work before I can merge it.  Here are my two concerns:

1) I'm not sure that "transparent" is the most transparent name for this flag, if you will. :)  I believe I understand the metaphor, but perhaps --nonbusy would frame things in the same language the api and calendar app use.  Or, there may be something better than that.  I'd love to get input from other users here.

2) As written, this breaks the tests.  If you need help refactoring so that things still pass (ideally, you'd add to the testsuite as well), let me know.

2020-01-29 06:06 UTC, kda commented
1. I'm willing to change it to --nonbusy.  I will give it a day or two for
input.
2. Yeah, I rushed it and only tested it manually for my application.  I
will improve the tests.

An etiquette and git question: (zero experience in the github world...)
Do I create a new branch?  (and create a new pull request?)
Do I just continue to work on the existing branch? (and give a holler when
I think it is ready to go.)

2020-01-29 06:23 UTC, jcrowgey commented
> 1. I'm willing to change it to --nonbusy. I will give it a day or two for input. 2. Yeah, I rushed it and only tested it manually for my application. I will improve the tests. An etiquette and git question: (zero experience in the github world...) Do I create a new branch? (and create a new pull request?) Do I just continue to work on the existing branch? (and give a holler when I think it is ready to go.)

No need to make a new PR.  I'm happy for you to manage things as you see fit.  Choose a new branch (you should be able to edit the PR to target a different source branch), or keep this branch and make changes.  Squash your commits if you like.  You can go so far as to force push and rewrite published history within your branch.  As long as you own the branch, I won't worry about it.

Thanks for the PR!  Looking forward to the changes.

2024-08-26 02:42 UTC, dbarnett commented
Oh yeah, I see it's called "transparency" in the API (https://developers.google.com/calendar/api/v3/reference/events#transparency) but in the UI it's called visibility=FREE|BUSY. I think that'll be the more discoverable name for most users. Could we change that to `--visibility=FREE|BUSY`?

LMK if you're planning to do that, otherwise I'll probably put together some changes to fix it.

2024-08-26 20:19 UTC, dbarnett commented
> I think that'll be the more discoverable name for most users. Could we change that to --visibility=FREE|BUSY?

Although weirdly Google seems to also refer to the privacy setting as "visibility" (public/private). Still, we should probably follow the naming they use in the actual UI and help docs and call this parameter "visibility".

2024-08-26 20:19 UTC, dbarnett requested changes
Please update the flag name as discussed.

LMK if you need help or would like someone else to take over on this change.

2025-02-22 19:41 UTC, closed without merging